// Generated by CoffeeScript 1.10.0
(function() {
  var WiFiScanner, execSyncToBuffer, os_instructions, private_context;

  WiFiScanner = require('node-wifiscanner2');

  execSyncToBuffer = require('sync-exec');

  switch (process.platform) {
    case "linux":
      os_instructions = require('./linux.js');
      break;
    case "win32":
      os_instructions = require('./win32.js');
      break;
    case "darwin":
      os_instructions = require('./darwin.js');
      break;
    default:
      WiFiLog("Unrecognized operating system.", true);
      process.exit();
  }

  private_context = {
    WiFiControlSettings: {
      iface: null,
      debug: false
    },
    execSync: function(command, options) {
      var results;
      if (options == null) {
        options = {};
      }
      results = execSyncToBuffer(command, options);
      if (!results.status) {
        return results.stdout;
      }
      throw {
        stderr: results.stderr
      };
    },
    WiFiLog: function(msg, error) {
      if (error == null) {
        error = false;
      }
      if (error) {
        return console.error("WiFiControl: " + msg);
      } else {
        if (this.WiFiControlSettings.debug) {
          return console.log("WiFiControl: " + msg);
        }
      }
    }
  };

  module.exports = {
    init: function(settings) {
      if (settings == null) {
        settings = {};
      }
      this.configure(settings);
      if (settings.iface == null) {
        return this.findInterface(settings.iface);
      }
    },
    configure: function(settings) {
      if (settings == null) {
        settings = {};
      }
      if (settings.debug != null) {
        private_context.WiFiControlSettings.debug = settings.debug;
        private_context.WiFiLog("Debug mode set to: " + settings.debug);
      }
      if (settings.iface != null) {
        return this.findInterface(settings.iface);
      }
    },
    findInterface: function(iface) {
      var _msg, error, error1, interfaceResults;
      if (iface == null) {
        iface = null;
      }
      try {
        if (iface != null) {
          _msg = "Wireless interface manually set to " + iface + ".";
          private_context.WiFiLog(_msg);
          private_context.WiFiControlSettings.iface = iface;
          return {
            success: true,
            msg: _msg,
            "interface": iface
          };
        }
        private_context.WiFiLog("Determining system wireless interface...");
        interfaceResults = os_instructions.autoFindInterface.call(private_context);
        private_context.WiFiControlSettings.iface = interfaceResults["interface"];
        return interfaceResults;
      } catch (error1) {
        error = error1;
        _msg = "Encountered an error while searching for wireless interface: " + error;
        private_context.WiFiLog(_msg, true);
        return {
          success: false,
          msg: _msg
        };
      }
    },
    scanForWiFi: function(cb) {
      var _msg, error, error1, networks;
      if (private_context.WiFiControlSettings.iface == null) {
        _msg = "You cannot scan for nearby WiFi networks without a valid wireless interface.";
        private_context.WiFiLog(_msg, true);
        return {
          success: false,
          msg: _msg
        };
      }
      try {
        private_context.WiFiLog("Scanning for nearby WiFi Access Points...");
        if (process.platform === "linux") {
          networks = os_instructions.scanForWiFi.apply(private_context);
          _msg = "Nearby WiFi APs successfully scanned (" + networks.length + " found).";
          private_context.WiFiLog(_msg);
          return cb(null, {
            success: true,
            msg: _msg,
            networks: networks
          });
        } else {
          return WiFiScanner.scan(function(err, networks) {
            if (err) {
              _msg = "We encountered an error while scanning for WiFi APs: " + error;
              private_context.WiFiLog(_msg, true);
              return cb(err, {
                success: false,
                msg: _msg
              });
            } else {
              _msg = "Nearby WiFi APs successfully scanned (" + networks.length + " found).";
              private_context.WiFiLog(_msg);
              return cb(null, {
                success: true,
                networks: networks,
                msg: _msg
              });
            }
          });
        }
      } catch (error1) {
        error = error1;
        _msg = "We encountered an error while scanning for WiFi APs: " + error;
        private_context.WiFiLog(_msg, true);
        return cb(error, {
          success: false,
          msg: _msg
        });
      }
    },
    connectToAP: function(_ap) {
      var _msg, error, error1, ifaceState;
      if (private_context.WiFiControlSettings.iface == null) {
        _msg = "You cannot connect to a WiFi network without a valid wireless interface.";
        private_context.WiFiLog(_msg, true);
        return {
          success: false,
          msg: _msg
        };
      }
      try {
        if (!_ap.ssid.length) {
          return {
            success: false,
            msg: "Please provide a non-empty SSID."
          };
        }
        if (_ap.password == null) {
          _ap.password = "";
        }
        os_instructions.connectToAP.call(private_context, _ap);
        private_context.WiFiLog("Waiting for connection attempt to settle...");
        while (true) {
          ifaceState = this.getIfaceState();
          if (ifaceState.success) {
            if (ifaceState.connection === "connected") {
              break;
            } else if (ifaceState.connection === "disconnected") {
              _msg = "Error: Interface is not currently connected to any wireless AP.";
              private_context.WiFiLog(_msg, true);
              return {
                success: false,
                msg: _msg
              };
            }
          }
        }
        if (ifaceState.ssid === _ap.ssid) {
          _msg = "Successfully connected to " + _ap.ssid + "!";
          private_context.WiFiLog(_msg);
          return {
            success: true,
            msg: _msg
          };
        } else {
          _msg = "Error: Interface is currently connected to " + ifaceState.ssid;
          private_context.WiFiLog(_msg, true);
          return {
            success: false,
            msg: _msg
          };
        }
      } catch (error1) {
        error = error1;
        _msg = "Encountered an error while connecting to " + _ap.ssid + ": " + error;
        private_context.WiFiLog(_msg, true);
        return {
          success: false,
          msg: _msg
        };
      }
    },
    resetWiFi: function() {
      var COMMANDS, _msg, com, error, error1, i, ifaceState, len, resetWiFiChain, stdout;
      try {
        switch (process.platform) {
          case "linux":
            COMMANDS = {
              disableNetworking: "nmcli networking off",
              enableNetworking: "nmcli networking on"
            };
            resetWiFiChain = ["disableNetworking", "enableNetworking"];
            break;
          case "win32":
            COMMANDS = {
              disconnect: "netsh " + WiFiControlSettings.iface + " disconnect"
            };
            resetWiFiChain = ["disconnect"];
            break;
          case "darwin":
            COMMANDS = {
              enableAirport: "networksetup -setairportpower " + WiFiControlSettings.iface + " on",
              disableAirport: "networksetup -setairportpower " + WiFiControlSettings.iface + " off"
            };
            resetWiFiChain = ["disableAirport", "enableAirport"];
        }
        for (i = 0, len = resetWiFiChain.length; i < len; i++) {
          com = resetWiFiChain[i];
          WiFiLog("Executing:\t" + COMMANDS[com]);
          stdout = execSync(COMMANDS[com]);
          _msg = "Success!";
          WiFiLog(_msg);
        }
        WiFiLog("Waiting for interface to finish resetting...");
        while (true) {
          ifaceState = this.getIfaceState();
          if (ifaceState.success) {
            if (ifaceState.power) {
              WiFiLog("Success!  Wireless interface is now reset.");
              break;
            }
          } else {
            _msg = "Error: Interface could not be reset.";
            WiFiLog(_msg, true);
            return {
              success: false,
              msg: _msg
            };
          }
        }
        return {
          success: true,
          msg: "Successfully reset WiFi!"
        };
      } catch (error1) {
        error = error1;
        _msg = "Encountered an error while resetting wireless interface: " + error;
        WiFiLog(_msg, true);
        return {
          success: false,
          msg: _msg
        };
      }
    },
    getIfaceState: function() {
      var _msg, error, error1, interfaceState;
      try {
        interfaceState = os_instructions.getIfaceState.call(private_context);
        if (interfaceState.success !== false) {
          interfaceState.success = true;
          interfaceState.msg = "Successfully acquired state of network interface " + private_context.WiFiControlSettings.iface + ".";
        }
        return interfaceState;
      } catch (error1) {
        error = error1;
        _msg = "Encountered an error while acquiring network interface connection state: " + error;
        private_context.WiFiLog(_msg, true);
        return {
          success: false,
          msg: _msg
        };
      }
    }
  };

}).call(this);
